"""
TN-LawMaster — Citation Hallucination Verifier
================================================
Verifies that TCA citations produced by the LLM actually exist in the
vector-store corpus before surfacing them to the user.

If a citation cannot be confirmed in the corpus (distance above the
configured threshold) it is flagged as *unverified* and a prominent
disclaimer is appended to the analysis text so callers / UIs can
surface this to the user.

Usage::

    from tn_law_agent.utils.citation_verifier import CitationVerifier

    verifier = CitationVerifier(ingester=my_ingester)
    result = verifier.verify(citations=["TCA § 39-14-105"], analysis=llm_text)
    print(result["verified"])
    print(result["unverified"])
    print(result["flagged_analysis"])
"""

from __future__ import annotations

import logging
import re
from typing import List, Optional

logger = logging.getLogger(__name__)

# ── Regex that matches TCA citations ─────────────────────────────────────────
# Handles forms such as:
#   TCA § 39-14-105
#   TCA § 39-14-105(a)
#   TCA §39-14-105
_TCA_CITATION_RE = re.compile(
    r"TCA\s*§\s*[\d]+-[\d]+-[\d]+(?:\([a-zA-Z0-9]+\))*",
    re.IGNORECASE,
)

# Default cosine-distance threshold below which we consider a citation "found"
# (ChromaDB cosine distances: 0 = identical, 2 = opposite; a score < 0.45 is a
# reasonable "close match" for a short citation string).
_DEFAULT_DISTANCE_THRESHOLD: float = 0.45


class CitationVerifier:
    """
    Verifies TCA citations generated by the LLM against the vector store corpus.

    For each citation the verifier performs a targeted similarity search.  If a
    matching chunk is found within ``distance_threshold`` the citation is
    classified as *verified*; otherwise it is *unverified* and a footnote is
    appended to the analysis.

    Args:
        ingester:            A ``TNLawIngester`` instance (or any object that
                             exposes a ``.search(query, top_k) -> List[dict]``
                             method).  When ``None`` all citations are returned
                             as unverified.
        distance_threshold:  Maximum cosine distance to consider a hit valid.
    """

    def __init__(
        self,
        ingester=None,
        distance_threshold: float = _DEFAULT_DISTANCE_THRESHOLD,
    ) -> None:
        self.ingester = ingester
        self.distance_threshold = distance_threshold

    # ── Public API ────────────────────────────────────────────────────────────

    def verify(self, citations: List[str], analysis: str) -> dict:
        """
        Verify a list of TCA citations against the corpus.

        Args:
            citations: List of citation strings (e.g. ``["TCA § 39-14-105"]``).
                       May also be extracted directly from *analysis* when you
                       pass an empty list.
            analysis:  The LLM-generated analysis text.

        Returns:
            A dict with three keys:

            - ``"verified"``        — citations confirmed in the corpus
            - ``"unverified"``      — citations NOT confirmed in the corpus
            - ``"flagged_analysis"``— original *analysis* with an appended
                                      disclaimer listing unverified citations
        """
        # Extract from analysis if no explicit list provided
        if not citations:
            citations = _TCA_CITATION_RE.findall(analysis)

        # Deduplicate while preserving order
        seen: set[str] = set()
        unique_citations: List[str] = []
        for c in citations:
            if c not in seen:
                seen.add(c)
                unique_citations.append(c)

        verified: List[str] = []
        unverified: List[str] = []

        for citation in unique_citations:
            if self._citation_exists(citation):
                verified.append(citation)
                logger.debug("[CitationVerifier] VERIFIED: %s", citation)
            else:
                unverified.append(citation)
                logger.warning("[CitationVerifier] UNVERIFIED: %s", citation)

        flagged_analysis = analysis
        if unverified:
            flagged_analysis = self._add_disclaimer(analysis, unverified)

        return {
            "verified": verified,
            "unverified": unverified,
            "flagged_analysis": flagged_analysis,
        }

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _citation_exists(self, citation: str) -> bool:
        """
        Search the corpus for *citation*.  Returns ``True`` if at least one
        result comes back within ``self.distance_threshold``.

        When no ingester is configured every citation is treated as unverified.
        """
        if self.ingester is None:
            logger.debug(
                "[CitationVerifier] No ingester configured — marking '%s' unverified.",
                citation,
            )
            return False

        try:
            results = self.ingester.search(citation, top_k=3)
        except Exception as exc:
            logger.warning(
                "[CitationVerifier] Search error for '%s': %s", citation, exc
            )
            return False

        if not results:
            return False

        # Check whether any result is close enough
        for hit in results:
            distance = hit.get("distance", float("inf"))
            if distance < self.distance_threshold:
                logger.debug(
                    "[CitationVerifier] '%s' confirmed (distance=%.4f)", citation, distance
                )
                return True

        return False

    def _add_disclaimer(self, analysis: str, unverified: List[str]) -> str:
        """
        Append a clearly visible disclaimer to *analysis* naming each citation
        that could not be confirmed in the corpus.

        Args:
            analysis:   Original LLM analysis string.
            unverified: Non-empty list of unverified citation strings.

        Returns:
            Analysis text with the disclaimer block appended.
        """
        citation_list = "\n".join(f"  • {c}" for c in unverified)
        disclaimer = (
            "\n\n---\n"
            "**⚠️ Citation Verification Notice**\n"
            "The following citation(s) could **not** be confirmed in the "
            "retrieved TCA corpus and may be hallucinated or refer to "
            "sections outside the currently ingested documents. "
            "Please verify independently before relying on them:\n\n"
            f"{citation_list}\n\n"
            "_Always consult the official Tennessee Code Annotated or a "
            "licensed Tennessee attorney to confirm statutory references._"
        )
        return analysis + disclaimer
